
name: cd

on:
    push:
        branches: [main]

jobs: 
    Deploy: 
        name: Deploy
        runs-on: ubuntu-latest

        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

        steps:
            - name: checkout
              uses: actions/checkout@v4
            
            - name: Install Go
              uses: actions/setup-go@v5
              with:
                go-version: '1.23.3'
            
            - name: Install goose for migrations
              run: go install github.com/pressly/goose/v3/cmd/goose@latest
              
            - name: Build production binary
              run: scripts/buildprod.sh

            - name: Migrate database up
              run: scripts/migrateup.sh
            
            - name: Authenticate with Google Cloud
              uses: google-github-actions/auth@v2
              with:
                credentials_json: ${{secrets.GCP_CREDENTIALS}}
            
            - name: Set up Cloud SDK
              uses: google-github-actions/setup-gcloud@v2
            
            - name: Deploy to Artifact Registry
              run: gcloud builds submit --tag us-central1-docker.pkg.dev/notely-442018/notely-ar-repo/notely:latest .
            
            - name: Deploy latest image to cloud run
              run: gcloud run deploy notely --image us-central1-docker.pkg.dev/notely-442018/notely-ar-repo/notely:latest --region us-central1 --allow-unauthenticated --project notely-442018 --max-instances=4
            - name: Git diff
              run: git diff 