
name: cd

on:
    push:
        branches: [main]

jobs: 
    Deploy: 
        name: Deploy
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              run: actions/checkout@v4
            
            - name: Install Go
              run: actions/setup-go@v5
              
            - name: Build production binary
              run: scripts/buildprod.sh
            
